title: Scrap & Trace
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

kramdown:
  math_engine: mathjax
  input: GFM
